name: "gRPC Bridge"
description: "Service that acts as a bridge between Home Assistant and other services. Translating gRPC calls into WebSocket commands."
version: c63dd7d
url: https://github.com/moonen-home-automation/grpc-bridge
slug: "grpc_bridge"
init: false
arch:
- amd64
homeassistant_api: true
ports:
  9091/tcp: 9091
ports_description:
  9091/tcp: gRPC
image: ghcr.io/moonen-home-automation/grpc-bridge/{arch}
